---
batch_size: 8
checkpoint_frequency: 5000
clip_grad_norm: 3.0
curriculum_end_step: 50000
do_full_eval_after: 75000
downsample_factor: 320
encoder: convnet
eval_after: 5
experiment_dir: /home/jupyter/drasdic/experiments/random_9
gradient_accumulation_batches_per_step: 1
hidden_size: 64
inputs: audio
log_every: 100
lr: 2.0e-05
mixed_precision: false
model_type: encoder_decoder
n_blocks: 1
n_ensemble_prompts: 1
n_mels: 256
n_shots: 5
n_steps_warmup: 10000
n_train_examples: 800000
n_train_steps: 100000
name: random_9
neg_proto_hop_dur: 2
num_workers: 12
previous_checkpoint_fp: /mnt/home/drasdic_api/weights/model_80000.pt
previous_encoder_fp: null
project_dir: /home/jupyter/drasdic/experiments/
query_duration_sec: 10
scene_generator_config_fp: /home/jupyter/drasdic/randomcfg_1/data_config_r9.yaml
seed: 8
sr: 16000
support_duration_sec: 30
support_features:
  - duration
support_selection_method: random
support_subchunk_size_sec: 5
test_data_parent_dir: null
test_directories:
  - /home/jupyter/data/fewshot_data/evaluation/formatted_for_dcase/ME
  - /home/jupyter/data/fewshot_data/evaluation/formatted_for_dcase/HB
  - /home/jupyter/data/fewshot_data/evaluation/formatted_for_dcase/PB24_halftime
  - /home/jupyter/data/fewshot_data/evaluation/formatted_for_dcase/PW
unfreeze_encoder_step: 0
val_directories:
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/BV
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/HB
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/HT
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/JD
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/ME
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/MT
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/PB
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/PB24
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/PW
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/RD
  - /home/jupyter/data/fewshot_data/validation/formatted/30_10_v1/WMW
val_frequency: 10000
wandb: false
window_len_sec: 10
